{% set name = "cryptopp" %}
{% set version = "5.6.5" %}
{% set sha256 = "79fd5514b3b191a1c6d934cd989d5e058f4726a72a3dad2444bd1274a6aae686" %}

package:
  name: {{ name| lower }}
  version: {{ version }}

source:
  fn: {{ name | upper }}-{{ version | replace('.', '_') }}.tar.gz
  url: https://github.com/weidai11/cryptopp/archive/{{ name | upper }}_{{ version | replace('.', '_') }}.tar.gz
  sha256: {{ sha256 }}

  patches:
    # Replaces flag -march=native with flag  -mtune=generic
    # This flag can be removed via cmake optino in the next release
    - 0001-cmake-mtune-fix.patch  # [not win]

build:
  number: 1004
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libcryptopp.a    # [unix]
    - test -d ${PREFIX}/include/cryptopp     # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config.cmake          # [unix]
    - test -f ${PREFIX}/lib/cmake/cryptopp/cryptopp-config-version.cmake  # [unix]
    - if exist %LIBRARY_LIB%\cryptopp-static.lib (exit 0) else (exit 1)       # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config.cmake (exit 0) else (exit 1)          # [win]
    - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config-version.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.cryptopp.com
  license: Boost-1.0
  license_file: License.txt
  summary: A C++ Class Library of Cryptographic Schemes

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
